name: Docker App CI

on:
  push:
    branches:
      - feature/add-CI-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t simple-flask-app .

      # Step 5: Run Docker container
      - name: Run Docker container
        run: docker run -d -e PORT=5002 -p 5002:5002 simple-flask-app
      

      # Step 6: Wait for the app to be ready (Optional, but useful)
      - name: Wait for app to be available
        run: |
          for i in {1..10}; do
            if curl --silent --fail http://localhost:5002; then
              echo "App is up and running!"
              break
            fi
            echo "Waiting for app to be ready..."
            sleep 5
          done

      # Step 7: Run tests
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v