name: Docker App CI

on:
  push:
    branches:
      - feature/add-CI-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t simple-flask-app .

      # Step 5: Run Docker container
      - name: Run Docker container
        run: docker run -d -e PORT=5002 -p 5002:5002 --name simple-flask-app -w /app simple-flask-app

      # Step 6: Wait for Flask to fully start (optional but recommended)
      - name: Wait for Flask to start
        run: sleep 10

      # Step 7: List running Docker containers
      - name: List running Docker containers
        run: docker ps
        
      # Step 8: Check Docker container logs
      - name: List files in /app
        run: docker exec simple-flask-app ls -R /app

      # Step 9: List Docker images to ensure the image was built correctly
      - name: List Docker images
        run: docker images

      # Step 10: Run tests
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v
